Add save_excel and save_csv methods to FitData object
EddLabs/eddington pull request #58
Opened 2020-08-24 20:46 UTC by OhadNir9

Solves #52 and #53

2020-08-25 06:15 UTC, saroad2 requested changes
Thank you for your contribution.

I left some comments. Please feel free to return a feedback or ask for help if needed.

2020-08-25 06:15 UTC, saroad2 commented on src/eddington/fit_data.py
> +    def __make_sheet(self, sheet=None):
There is no separate logic here that may be called in more than one place.

You can move the entire section to the `save_excel` method

2020-08-25 06:15 UTC, saroad2 commented on src/eddington/fit_data.py
> +        :param output_directory: str or Path.
Specify the type of the parameter in a `:type:` section.

2020-08-25 06:15 UTC, saroad2 commented on src/eddington/fit_data.py
> +        worksheet = self.__make_sheet()[1]
There is no need to make a worksheet here, especially if you drop it emidiatly after.

I would recommend you use [DictWriter](https://docs.python.org/3/library/csv.html#csv.DictWriter) in order to write the csv file.

2020-08-25 06:15 UTC, saroad2 commented on src/eddington/fit_result.py
> +class FitResult:  # pylint: disable=too-many-instance-attributes
This fix is not relevant to this new feature and it should be in a different PR

2020-08-25 06:15 UTC, saroad2 commented on tests/fit_data/test_save_data_to_file.py
> +from pathlib import Path
Those are actually very solid **integration tests**.

One key element of **unit tests** is that they don't interact with the operating system (aka, read and write files).
*Integration tests* however, do exactly that. They test the software end-to-end and see that the different components combine nicely together.

Please keep those tests as they are, but move them to the *integration_tests* directory (if it's missing in your branch, update the master branch from upstream, and merge it into your feature branch. I added this directory yesterday).

After you do that, write new unit tests, but use [mocks](https://realpython.com/python-mock-library/) in order to simulate writing to a file.

Mocks can sometimes be perceived as a little bit hard concept for developers who are not familiar with them. Please feel free to say that you rather I will write the unit tests for you, and I'll step right in.

2020-08-25 07:54 UTC, saroad2 requested changes

2020-08-25 07:54 UTC, saroad2 commented on src/eddington/fit_data.py
> +    def save_csv(self, output_directory, name=None):
use default `name="fit_data.csv"`

2020-08-25 07:54 UTC, saroad2 commented on src/eddington/fit_data.py
> +            path = Path(output_directory / "FitData.csv")
Remove this if-else statement and use default value in the method signature

2020-08-25 07:54 UTC, saroad2 commented on src/eddington/fit_data.py
> +    def save_excel(self, output_directory, name=None, sheet=None):
use `name="fit_data.xlsx"`

2020-08-25 07:54 UTC, saroad2 commented on src/eddington/fit_data.py
> +            path = Path(output_directory / "FitData.xlsx")
Remove if-else statement and use method signature default instead.

2020-08-27 20:41 UTC, OhadNir9 commented
I'm having trouble with the mock concept, if it's ok I prefer you'll do it. I moved the test file to integration_tests.
Moreover, as you requested I removed the pylint comment from fit_result.

2020-08-28 05:58 UTC, saroad2 approved these changes
Thank you for your contribution!

I added the missing unit tests and fixed some small issues.

2020-08-28 05:58 UTC, merged